apiVersion: v1
kind: Service
metadata:
  labels:
    app: zmq-service-sub
  name: zmq-service
spec:
  selector:
    app: zmq_sub
  type: LoadBalancer
  externalIPs:
    - 172.18.255.200
  ports:
    - protocol: TCP
      port: 802
      nodePort: 30000
