apiVersion: v1
kind: Service
metadata:
  labels:
    app: zmq-service-sub
  name: zmq-service
spec:
  selector:
    app: zmq_sub
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 802
      port: 802
      nodePort: 30000
